<a href="https://colab.research.google.com/github/sinkerball/ImageProcessing/blob/master/%ED%9E%88%EC%8A%A4%ED%86%A0%EA%B7%B8%EB%9E%A8_%ED%8F%89%ED%99%9C%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import cv2
import numpy as np

src = np.array([[3,2,2,2,2,3,3,4],
               [3,2,2,2,3,4,3,3],
               [4,3,3,4,4,4,3,3],
               [5,4,4,4,5,4,3,3],
               [5,4,3,4,5,4,3,2],
               [6,5,4,4,5,4,3,2],
               [6,6,5,5,4,3,2,2],
               [6,5,4,5,4,3,2,2]], dtype = np.uint8)

dst= cv2. equalizeHist (src)
print(dst)

[[ 90   0   0   0   0  90  90 185]
 [ 90   0   0   0  90 185  90  90]
 [185  90  90 185 185 185  90  90]
 [235 185 185 185 235 185  90  90]
 [235 185  90 185 235 185  90   0]
 [255 235 185 185 235 185  90   0]
 [255 255 235 235 185  90   0   0]
 [255 235 185 235 185  90   0   0]]
